import type { Metadata } from 'next';
import { Urbanist, Nunito_Sans, Petit_Formal_Script } from 'next/font/google';
import './globals.css';
import Navbar from '../../components/layout/Navbar';

const urbanist = Urbanist({
  variable: '--font-urbanist',
  subsets: ['latin'],
});

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
  weight: ['400'], // Specify the weights you need (Petit Formal Script only has 400)
  display: 'swap', // 'swap' is recommended to avoid layout shifts
});

const petitFormalScript = Petit_Formal_Script({
  variable: '--font-petit-formal-script',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${nunitoSans.variable} ${petitFormalScript.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
